# Generated by Django 2.2.7 on 2019-11-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='user_name',
            field=models.CharField(default='NULL', max_length=10),
        ),
    ]
